[package]
name = "ripgit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
flate2 = "1.0.35"
rust-ini = "0.21.1"
tempdir = "0.3.7"
